### ISSUE TITLE
Allow setting alias on send_nym

### ISSUE THREAD

**Issue by nrempel** [PSPC-SPAC-buyandsell/von_agent#1]
It looks like it should be fairly easy to allow the caller to set an alias on a NYM request.

Would you be able to add that feature?

https://github.com/PSPC-SPAC-buyandsell/von_agent/blob/master/von_agent/agents.py#L628

**Comment by sklump** [comment]
Sure, Nick. I just came across this request a moment ago. I'll bake it into the next micro release.

**Comment by sklump** [comment]
I've plumbed in the update, but the indy-sdk ignores the alias at present. As soon as an indy-sdk update fulfills (and I pick it up in von_base), it will appear on the ledger.

**Comment by nrempel** [comment]
Beauty! I forgot I asked this :)

Sounds good.
