### ISSUE TITLE
Add multi-DID support to wallet

### ISSUE THREAD

**Issue by hidde-jan** [PSPC-SPAC-buyandsell/von_agent#2]
Hi people,

This really is an amazing project you've got going in here. I understand this is for a specific use-case, but since working with indy-sdk directly is quite a chore, this project might also be very interesting for people trying to work with indy/sovrin. Are you open to accepting PRs might increase the usability outside your own use-case?

As a start, I've tried to add multi-DID support to the wallet (whatever that means) here: https://github.com/hidde-jan/von_agent/commit/e011bf74718616c7ee30c54261d969300fe94f31

It currently depends on a pull request in the indy-sdk repository extending the python wrapper with some missing capabilities: https://github.com/hyperledger/indy-sdk/pull/532

Do you think multiple dids is something you want to support? Is this a step in the right direction or do you think there would need to be a different/cleaner/more complete solution altogether?

Cheers,
HJ

**Comment by britthurley** [comment]
Hey!

Thanks for your interest! We also saw some of your conversation on the indy-sdk Rocketchat - great discussion.

This work is currently happening in collaboration between ourselves in the Canadian Federal Government and our friends over in BC. More information will be made available here: https://von.pathfinder.gov.bc.ca/

Mr. @sklump is our primary indy-sdk Dev - you should be able to find him lurking around on Rocketchat, and some other members there, and in the various calls as well.  We're looking in the coming days about defining how we can contribute and interact with the community so your interest is well timed. I'll share you feedback with the group and get back to you!

Britt

**Comment by britthurley** [comment]
And from @sklump:

"At present our model is 1:1, agent to DID. There may be some use case for multiple DIDs per agent at some future juncture, but it's not up to me.

Note that the document in https://github.com/PSPC-SPAC-buyandsell/von_base/doc/agent-design.doc outlines our use cases and details the installation and use of the von_agent and its associated reference von_connector (RESTful API) implementation.

Thanks for the interest!"
